### ISSUE TITLE
PHP Fatal error when returning WP_Error

### ISSUE THREAD

**Issue by dd32** [CastosHQ/Seriously-Simple-Podcasting#723]
**Describe the bug**
E_ERROR: Uncaught Error: Class 'SeriouslySimplePodcasting\Rest\WP_Error' not found in wp-content/plugins/seriously-simple-podcasting/php/classes/rest/class-episodes-controller.php:496

```
Stack trace:
#0 wp-includes/rest-api/class-wp-rest-request.php(910): SeriouslySimplePodcasting\Rest\Episodes_Controller->validate_user_can_query_private_statuses('JJJ22QQQ', Object(WP_REST_Request), 'status')
#1 wp-includes/rest-api/class-wp-rest-server.php(976): WP_REST_Request->has_valid_params()
#2 wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 wp-includes/rest-api.php(370): WP_REST_Server->serve_request('/ssp/v1/episode...')
#4 wp-includes/class-wp-hook.php(303): rest_api_loaded(Object(WP))
#5 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#6 wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#7 wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#8 wp-includes/class-wp.php(750): WP->parse_request('')
#9 wp-includes/functions.php(1291): WP->main('')
#10 wp-blog-header.php(16): wp()
#11 index.php(26): require('index.php')
#12 {main}
 thrown
Source: GET https://example.org/wp-json/ssp/v1/episodes?id=JJJ0QQQ&action=JJJ1QQQ&page=JJJ2QQQ&name=JJJ3QQQ&f=JJJ4QQQ&url=J...
```

Looks like it just doesn't import `WP_Error`. Probably worth checking for other instances.

**To Reproduce**
Trigger the WP_Error condition in the REST API endpoint

**Expected behavior**
Not fatal.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zahardev** [comment]
Hi @dd32! Thanks for bringing it to our attention. It will be fixed in the next release.
